### ISSUE TITLE
Return type of last error

### ISSUE THREAD

**Issue by paspetsch** [COMPREDICT-GmbH/ai-sdk-php#8]
I'm not sure if return type `string` of Client::getLastError is correct. It actually returns an object like

```
{
  +"errors": array:1 [
    0 => "features : Input name: `***` is mandatory but not provided!"
  ]
  +"status": false
}
```

which then causes a 500 instead of responding with the error.

[In current code](https://github.com/COMPREDICT-GmbH/ai-sdk-php/blob/master/src/API/Algorithms/Client.php#L114)
[In History](https://github.com/COMPREDICT-GmbH/ai-sdk-php/commit/eb71654cfcb4eba4554f75448895b524df8b79ba#diff-dcead87f6d7b7e05efda6a0009e03410cece7268ae64c975bdea6d4b9cfe0dd0R114)

**Comment by uzi0espil** [comment]
Yes you are right, based on [here](https://github.com/COMPREDICT-GmbH/ai-sdk-php/blob/b80d4f287077727cdfdc540a14f6f5d5d81a9712/src/API/Algorithms/Request.php#L565). It sets the lastError to the response which is then a JSON object. 

Can you create a PR to fix this.
